spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-156-110-139.compute-1.amazonaws.com:5432/d7equtc5j0cbgf
    username: uyhjigrxydyzqv
    password: 87c3b8e410a526643bad48af1fd878c2ae9317417663d2c4e7404f333e38cab2
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true